name: Playwright Tests
on:
  push:
    branches: [ main, master ]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npx playwright test
    
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results

    - name: Upload Allure Report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report

    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/index.html
        retention-days: 30
    
    - name: Upload Playwright Traces
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/**/*.zip
        retention-days: 7
      